---
label: Recipe
hide_body: false
is_partial: false
fields:
- type: text
  default: Title
- type: textarea
  label: Content
  name: content
  description: Text
  config:
    wysiwyg: true
    schema:
      format: markdown
    required: true
- type: tag_list
  name: Tags
